#!/usr/bin/env python3
"""Stage and validate ghd release assets generated by GoReleaser."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
import tomllib
from pathlib import Path
from typing import Any


EXPECTED_PLATFORMS = (
    ("darwin", "amd64"),
    ("darwin", "arm64"),
    ("linux", "amd64"),
    ("linux", "arm64"),
)
EXPECTED_ASSET_COUNT = 9


class StageError(RuntimeError):
    """Raised when release asset staging cannot continue."""


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", required=True, help="Release tag, for example v1.2.3")
    parser.add_argument("--artifacts", default=Path("dist/artifacts.json"), type=Path)
    parser.add_argument("--config", default=Path("ghd.toml"), type=Path)
    parser.add_argument("--output", default=Path("dist/release-assets"), type=Path)
    parser.add_argument("--binary-name", default="template-go")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        stage_release_assets(
            tag=args.tag,
            artifacts_path=args.artifacts,
            config_path=args.config,
            output_dir=args.output,
            binary_name=args.binary_name,
        )
    except StageError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1
    return 0


def stage_release_assets(
    *,
    tag: str,
    artifacts_path: Path,
    config_path: Path,
    output_dir: Path,
    binary_name: str,
) -> None:
    version = release_version(tag)
    repository = os.environ.get("GITHUB_REPOSITORY")
    if not repository:
        raise StageError("GITHUB_REPOSITORY must be set")

    config = load_toml(config_path)
    validate_ghd_config(config, binary_name=binary_name, repository=repository)

    artifacts = load_artifacts(artifacts_path)
    stage_artifacts(artifacts, output_dir=output_dir, binary_name=binary_name)

    expected_binaries = verify_expected_assets(
        output_dir=output_dir,
        binary_name=binary_name,
        version=version,
    )
    verify_checksums(output_dir, expected_binaries)

    for path in sorted(path for path in output_dir.iterdir() if path.is_file()):
        print(path.as_posix())


def release_version(tag: str) -> str:
    if not tag.startswith("v") or tag == "v":
        raise StageError(f"could not resolve release version from {tag}")
    return tag[1:]


def load_toml(path: Path) -> dict[str, Any]:
    try:
        with path.open("rb") as config_file:
            data = tomllib.load(config_file)
    except FileNotFoundError as exc:
        raise StageError(f"missing ghd config {path}") from exc
    except tomllib.TOMLDecodeError as exc:
        raise StageError(f"invalid TOML in {path}: {exc}") from exc

    if not isinstance(data, dict):
        raise StageError(f"ghd config {path} must be a TOML table")
    return data


def load_artifacts(path: Path) -> list[dict[str, Any]]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise StageError(f"missing GoReleaser artifacts file {path}") from exc
    except json.JSONDecodeError as exc:
        raise StageError(f"invalid JSON in {path}: {exc}") from exc

    if not isinstance(data, list):
        raise StageError(f"{path} must contain a JSON array")

    artifacts: list[dict[str, Any]] = []
    for index, item in enumerate(data):
        if not isinstance(item, dict):
            raise StageError(f"{path} entry {index} must be an object")
        artifacts.append(item)
    return artifacts


def validate_ghd_config(config: dict[str, Any], *, binary_name: str, repository: str) -> None:
    provenance = config.get("provenance")
    if not isinstance(provenance, dict):
        raise StageError("ghd.toml must define a [provenance] table")

    expected_signer = f"{repository}/.github/workflows/attest.yml"
    actual_signer = provenance.get("signer_workflow")
    if actual_signer != expected_signer:
        raise StageError(
            f"ghd.toml signer_workflow must be {expected_signer}, got {actual_signer}"
        )

    package = find_package(config, binary_name)
    if package.get("tag_pattern") != "v${version}":
        raise StageError(
            f"ghd.toml package {binary_name!r} must use tag_pattern = \"v${{version}}\""
        )

    binaries = package.get("binaries")
    if not isinstance(binaries, list) or not any(
        isinstance(binary, dict) and binary.get("path") == binary_name for binary in binaries
    ):
        raise StageError(
            f"ghd.toml package {binary_name!r} must include binary path {binary_name!r}"
        )

    assets = package.get("assets")
    if not isinstance(assets, list):
        raise StageError(f"ghd.toml package {binary_name!r} must include assets")

    actual_patterns = {
        asset.get("pattern")
        for asset in assets
        if isinstance(asset, dict) and isinstance(asset.get("pattern"), str)
    }
    expected_patterns = {
        f"{binary_name}_${{version}}_{goos}_{goarch}" for goos, goarch in EXPECTED_PLATFORMS
    }
    missing_patterns = sorted(expected_patterns - actual_patterns)
    if missing_patterns:
        raise StageError(f"ghd.toml is missing expected asset pattern(s): {', '.join(missing_patterns)}")


def find_package(config: dict[str, Any], binary_name: str) -> dict[str, Any]:
    packages = config.get("packages")
    if not isinstance(packages, list):
        raise StageError("ghd.toml must define at least one [[packages]] entry")

    matches = [
        package
        for package in packages
        if isinstance(package, dict) and package.get("name") == binary_name
    ]
    if len(matches) != 1:
        raise StageError(f"ghd.toml must define exactly one package named {binary_name!r}")

    return matches[0]


def stage_artifacts(
    artifacts: list[dict[str, Any]],
    *,
    output_dir: Path,
    binary_name: str,
) -> None:
    output_dir.mkdir(parents=True, exist_ok=True)
    asset_prefix = f"{binary_name}_"
    staged_names: set[str] = set()

    for artifact in artifacts:
        artifact_type = artifact.get("type")
        artifact_name = artifact.get("name")
        artifact_path = artifact.get("path")

        if not isinstance(artifact_type, str) or not isinstance(artifact_name, str):
            continue

        destination_name: str | None = None
        executable = False
        if artifact_type == "Binary" and artifact_name.startswith(asset_prefix):
            destination_name = artifact_name
            executable = True
        elif artifact_type == "SBOM" and artifact_name.startswith(asset_prefix):
            if not isinstance(artifact_path, str):
                raise StageError(f"SBOM artifact {artifact_name!r} is missing a path")
            destination_name = Path(artifact_path).name
        elif artifact_type == "Checksum" and artifact_name == "checksums.txt":
            destination_name = "checksums.txt"

        if destination_name is None:
            continue
        if not isinstance(artifact_path, str):
            raise StageError(f"{artifact_type} artifact {artifact_name!r} is missing a path")
        if destination_name in staged_names:
            raise StageError(f"duplicate staged release asset name {destination_name!r}")

        source = Path(artifact_path)
        if not source.is_absolute():
            source = Path.cwd() / source
        if not source.is_file():
            raise StageError(f"missing GoReleaser artifact {artifact_path}")

        destination = output_dir / destination_name
        shutil.copy2(source, destination)
        if executable:
            destination.chmod(0o755)
        staged_names.add(destination_name)


def verify_expected_assets(*, output_dir: Path, binary_name: str, version: str) -> set[str]:
    expected_files = {"checksums.txt"}
    expected_binaries: set[str] = set()
    for goos, goarch in EXPECTED_PLATFORMS:
        binary = f"{binary_name}_{version}_{goos}_{goarch}"
        sbom = f"{binary}.sbom.json"
        expected_files.update({binary, sbom})
        expected_binaries.add(binary)

        binary_path = output_dir / binary
        if not binary_path.is_file():
            raise StageError(f"missing expected binary asset {binary}")
        if not os.access(binary_path, os.X_OK):
            raise StageError(f"expected binary asset is not executable: {binary}")

        sbom_path = output_dir / sbom
        if not sbom_path.is_file():
            raise StageError(f"missing expected SBOM asset {sbom}")

    staged_files = {path.name for path in output_dir.iterdir() if path.is_file()}
    if "checksums.txt" not in staged_files:
        raise StageError("missing staged checksums.txt")

    if len(staged_files) != EXPECTED_ASSET_COUNT:
        staged = ", ".join(sorted(staged_files))
        raise StageError(
            f"expected {EXPECTED_ASSET_COUNT} draft release assets, "
            f"found {len(staged_files)}: {staged}"
        )

    unexpected_files = sorted(staged_files - expected_files)
    if unexpected_files:
        raise StageError(f"unexpected staged release asset(s): {', '.join(unexpected_files)}")

    return expected_binaries


def verify_checksums(output_dir: Path, expected_binaries: set[str]) -> None:
    checksums = parse_checksums(output_dir / "checksums.txt")
    missing_checksums = sorted(expected_binaries - checksums.keys())
    if missing_checksums:
        raise StageError(f"missing checksum entry for expected binary asset(s): {', '.join(missing_checksums)}")

    for name, expected_digest in sorted(checksums.items()):
        path = output_dir / name
        if not path.is_file():
            raise StageError(f"checksum references unstaged file {name}")

        actual_digest = sha256_file(path)
        if actual_digest != expected_digest.lower():
            raise StageError(
                f"checksum mismatch for {name}: expected {expected_digest}, got {actual_digest}"
            )


def parse_checksums(path: Path) -> dict[str, str]:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()
    except FileNotFoundError as exc:
        raise StageError("missing staged checksums.txt") from exc

    checksums: dict[str, str] = {}
    for line_number, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not stripped:
            continue

        parts = stripped.split(None, 1)
        if len(parts) != 2:
            raise StageError(f"invalid checksums.txt line {line_number}: {line}")

        digest, raw_name = parts
        name = checksum_file_name(raw_name)
        if len(digest) != 64 or any(character not in "0123456789abcdefABCDEF" for character in digest):
            raise StageError(f"invalid sha256 digest for {name} on checksums.txt line {line_number}")
        if name in checksums:
            raise StageError(f"duplicate checksum entry for {name}")
        checksums[name] = digest

    if not checksums:
        raise StageError("checksums.txt does not contain any checksum entries")
    return checksums


def checksum_file_name(raw_name: str) -> str:
    name = raw_name.strip()
    if name.startswith("*"):
        name = name[1:]

    path = Path(name)
    if path.is_absolute() or path.name != name or ".." in path.parts:
        raise StageError(f"checksum entry must name a staged file, got {raw_name!r}")
    return name


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


if __name__ == "__main__":
    raise SystemExit(main())
