// Package mocks holds the generated test doubles for the ports in
// [github.com/meigma/terraform-provider-example/internal/core].
//
// Everything else in this package is generated by mockery from .mockery.yml
// and must not be edited by hand. Regenerate it after changing a port:
//
//	mise exec -- mockery
package mocks
