// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/meigma/terraform-provider-example/internal/core"
	mock "github.com/stretchr/testify/mock"
)

// NewStore creates a new instance of Store. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *Store {
	mock := &Store{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

type Store_Expecter struct {
	mock *mock.Mock
}

func (_m *Store) EXPECT() *Store_Expecter {
	return &Store_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type Store
func (_mock *Store) Create(ctx context.Context, item core.Item) (core.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.Item) (core.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.Item) core.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Get(0).(core.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Store_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - item core.Item
func (_e *Store_Expecter) Create(ctx any, item any) *Store_Create_Call {
	return &Store_Create_Call{Call: _e.mock.On("Create", ctx, item)}
}

func (_c *Store_Create_Call) Run(run func(ctx context.Context, item core.Item)) *Store_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.Item
		if args[1] != nil {
			arg1 = args[1].(core.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_Create_Call) Return(item1 core.Item, err error) *Store_Create_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *Store_Create_Call) RunAndReturn(run func(ctx context.Context, item core.Item) (core.Item, error)) *Store_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type Store
func (_mock *Store) Delete(ctx context.Context, id core.ID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Store_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Store_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id core.ID
func (_e *Store_Expecter) Delete(ctx any, id any) *Store_Delete_Call {
	return &Store_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *Store_Delete_Call) Run(run func(ctx context.Context, id core.ID)) *Store_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.ID
		if args[1] != nil {
			arg1 = args[1].(core.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_Delete_Call) Return(err error) *Store_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Store_Delete_Call) RunAndReturn(run func(ctx context.Context, id core.ID) error) *Store_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type Store
func (_mock *Store) Get(ctx context.Context, id core.ID) (core.Item, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ID) (core.Item, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.ID) core.Item); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(core.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.ID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Store_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id core.ID
func (_e *Store_Expecter) Get(ctx any, id any) *Store_Get_Call {
	return &Store_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *Store_Get_Call) Run(run func(ctx context.Context, id core.ID)) *Store_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.ID
		if args[1] != nil {
			arg1 = args[1].(core.ID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_Get_Call) Return(item core.Item, err error) *Store_Get_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *Store_Get_Call) RunAndReturn(run func(ctx context.Context, id core.ID) (core.Item, error)) *Store_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type Store
func (_mock *Store) GetByName(ctx context.Context, name core.Name) (core.Item, error) {
	ret := _mock.Called(ctx, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.Name) (core.Item, error)); ok {
		return returnFunc(ctx, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.Name) core.Item); ok {
		r0 = returnFunc(ctx, name)
	} else {
		r0 = ret.Get(0).(core.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.Name) error); ok {
		r1 = returnFunc(ctx, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type Store_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - name core.Name
func (_e *Store_Expecter) GetByName(ctx any, name any) *Store_GetByName_Call {
	return &Store_GetByName_Call{Call: _e.mock.On("GetByName", ctx, name)}
}

func (_c *Store_GetByName_Call) Run(run func(ctx context.Context, name core.Name)) *Store_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.Name
		if args[1] != nil {
			arg1 = args[1].(core.Name)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_GetByName_Call) Return(item core.Item, err error) *Store_GetByName_Call {
	_c.Call.Return(item, err)
	return _c
}

func (_c *Store_GetByName_Call) RunAndReturn(run func(ctx context.Context, name core.Name) (core.Item, error)) *Store_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type Store
func (_mock *Store) Update(ctx context.Context, item core.Item) (core.Item, error) {
	ret := _mock.Called(ctx, item)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 core.Item
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.Item) (core.Item, error)); ok {
		return returnFunc(ctx, item)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.Item) core.Item); ok {
		r0 = returnFunc(ctx, item)
	} else {
		r0 = ret.Get(0).(core.Item)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, core.Item) error); ok {
		r1 = returnFunc(ctx, item)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Store_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Store_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - item core.Item
func (_e *Store_Expecter) Update(ctx any, item any) *Store_Update_Call {
	return &Store_Update_Call{Call: _e.mock.On("Update", ctx, item)}
}

func (_c *Store_Update_Call) Run(run func(ctx context.Context, item core.Item)) *Store_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.Item
		if args[1] != nil {
			arg1 = args[1].(core.Item)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Store_Update_Call) Return(item1 core.Item, err error) *Store_Update_Call {
	_c.Call.Return(item1, err)
	return _c
}

func (_c *Store_Update_Call) RunAndReturn(run func(ctx context.Context, item core.Item) (core.Item, error)) *Store_Update_Call {
	_c.Call.Return(run)
	return _c
}
